// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuqoyglgvvlpcxikrpht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cW95Z2xndnZscGN4aWtycGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzkxMTYsImV4cCI6MjA2MDAxNTExNn0.HkWpTscvglt0CNMUrfjrIDu4ILFkMDm9Xy7-0r60phY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);